from . import product_brand
from . import pos_membership_level
from . import pos_retail_inventory_movement
from . import pos_retail_expense
from . import pos_retail_discount_role
from . import pos_retail_discount_reason
from . import pos_retail_return_reason
from . import pos_retail_price_reason
from . import pos_retail_discount_log
from . import product_template
from . import product_product
from . import product_supplierinfo
from . import res_partner
from . import sale_order
from . import purchase_order
from . import hr_employee
from . import pos_order
from . import pos_config
from . import pos_session
from . import pos_retail_dashboard
from . import res_users
