from odoo import _, api, models


class PosCategory(models.Model):
    _inherit = 'pos.category'

    @api.model
    def get_import_templates(self):
        """Offer a ready-made spreadsheet on the till-category Import screen.

        Separate from product.category on purpose: these are the button groups on
        the POS screen, a different model with a different shape (display order,
        button colour). Generated by tools/import_templates.py, served live by controllers/import_template.py.
        """
        return [{
            'label': _("Till Category Import Template"),
            'template': '/pos_retail/import-template/pos_category.xlsx',
        }]
