from odoo import _, api, models


class ProductCategory(models.Model):
    _inherit = 'product.category'

    @api.model
    def get_import_templates(self):
        """Offer a ready-made spreadsheet on the category Import screen.

        Categories have to exist before products can reference them, so a shop
        setting itself up loads this file first. Generated by
        tools/import_templates.py, served live by controllers/import_template.py.
        """
        return [{
            'label': _("Product Category Import Template"),
            'template': '/pos_retail/import-template/product_category.xlsx',
        }]
