"""Measurement-based selling: classify a product by what it is measured in.

Odoo 19 already answers most of the "multi-UoM" problem and this module must not
re-answer it:

  * base inventory unit          -> product.template.uom_id
  * extra sellable units         -> product.template.uom_ids
  * per-product pack + barcode   -> product.uom (extended in product_uom.py)
  * conversion between units     -> uom.uom.relative_factor chain + _compute_quantity
  * purchase in a vendor's unit  -> product.supplierinfo (uom_po_id was REMOVED in 19)
  * stock in the base unit       -> stock.move / stock.move.line

What Odoo does NOT have is a notion of what KIND of thing a product is measured
in. It knows a pipe is counted in metres, but not that "metres" means the till
should offer a decimal keypad and 0.5/1/2/5 m shortcuts instead of a [-] 1 [+]
stepper. That classification is what this file adds, and it is derived from the
unit's own conversion root so it cannot drift out of step with reality.
"""
from odoo import _, api, fields, models
from odoo.exceptions import ValidationError

# Measurement kinds, in the order a hardware shop meets them.
MEASUREMENT_TYPES = [
    ('piece', "Piece"),
    ('length', "Length"),
    ('weight', "Weight"),
    ('area', "Area"),
    ('volume', "Volume"),
    ('box', "Box"),
    ('carton', "Carton"),
    ('bundle', "Bundle"),
    ('roll', "Roll"),
    ('set', "Set"),
    ('custom', "Custom"),
]

# Kinds whose quantities are naturally fractional. A shop sells 2.75 m of pipe
# but never 2.75 taps, and letting a stepper hand back 0.5 of a toilet seat is
# how stock goes wrong.
DECIMAL_TYPES = {'length', 'weight', 'area', 'volume'}

# Conversion root -> measurement kind. The root is found by walking
# relative_uom_id upwards, so this survives new units being added underneath.
ROOT_XMLID_TO_TYPE = {
    'uom.product_uom_unit': 'piece',
    'uom.product_uom_millimeter': 'length',
    'uom.product_uom_gram': 'weight',
    'uom.product_uom_square_meter': 'area',
    'uom.product_uom_milliliter': 'volume',
}

# Sensible starting shortcuts per kind (section 10). Deliberately plain text so
# a shopkeeper can retype them without a wizard.
DEFAULT_QUICK_QTY = {
    'length': '0.5, 1, 2, 5, 10',
    'weight': '0.5, 1, 5, 10, 25',
    'area': '1, 5, 10, 25, 50',
    'volume': '0.5, 1, 4, 10, 20',
}


class UomUom(models.Model):
    _inherit = 'uom.uom'

    def _pos_retail_root(self):
        """The unit at the top of this unit's conversion chain.

        Two units are convertible only if they share a root, so the root is also
        the honest definition of "what kind of thing this measures".
        """
        self.ensure_one()
        unit, seen = self, set()
        while unit.relative_uom_id and unit.id not in seen:
            seen.add(unit.id)
            unit = unit.relative_uom_id
        return unit

    def _pos_retail_measurement_type(self):
        """Classify this unit as piece / length / weight / area / volume / custom."""
        self.ensure_one()
        root = self._pos_retail_root()
        for xmlid, kind in ROOT_XMLID_TO_TYPE.items():
            ref = self.env.ref(xmlid, raise_if_not_found=False)
            if ref and ref.id == root.id:
                return kind
        return 'custom'

    @api.model
    def get_import_templates(self):
        """Offer a ready-made spreadsheet on the Units Import screen.

        Generated by tools/import_templates.py, served live by controllers/import_template.py. It deliberately omits
        Absolute Quantity (factor): that is computed from the reference chain,
        and a column inviting a value that contradicts the chain would be a trap.
        """
        return [{
            'label': _("Unit of Measure Import Template"),
            'template': '/pos_retail/import-template/uom.xlsx',
        }]

    @api.model
    def _pos_retail_activate_trade_units(self):
        """Un-archive the units a hardware shop needs, which Odoo ships disabled.

        This has to be code rather than <record active="True"/>. Core's own
        ir_model_data rows for these units carry noupdate=True, and
        _load_records honours that flag whatever the calling data file says, so
        a record write is silently discarded on every existing database. That
        failure is invisible: the upgrade reports success and the units stay
        hidden. A <function> is not routed through ir_model_data at all.

        Called from data/pos_retail_uom_measurement_data.xml on install and on
        every upgrade. Idempotent, but note it re-activates: if you archive one
        of these deliberately, it will come back on the next upgrade. Remove the
        xmlid from the list below if you never want it.
        """
        xmlids = (
            'uom.product_uom_cm', 'uom.product_uom_inch',
            'uom.product_uom_foot', 'uom.product_uom_yard',
            'uom.product_uom_square_foot',
            'uom.product_uom_gal', 'uom.product_uom_cubic_meter',
            'uom.product_uom_cubic_foot',
        )
        units = self.browse()
        for xmlid in xmlids:
            unit = self.env.ref(xmlid, raise_if_not_found=False)
            if unit and not unit.active:
                units |= unit
        if units:
            units.action_unarchive()
        return True


class ProductTemplate(models.Model):
    _inherit = 'product.template'

    pos_retail_measurement_type = fields.Selection(
        MEASUREMENT_TYPES,
        string="Measurement Type",
        compute='_compute_pos_retail_measurement_type',
        store=True, readonly=False,
        help="What kind of thing this item is measured in. It decides how the "
             "till asks for a quantity: a stepper for pieces, a decimal keypad "
             "with shortcuts for metres, kilos, square feet and litres. Worked "
             "out from the Unit automatically; override it only for something "
             "the unit cannot express, such as a boxed item counted in Units "
             "that you still want treated as a Box.",
    )
    pos_retail_allow_decimal = fields.Boolean(
        string="Allow Decimal Quantity",
        compute='_compute_pos_retail_allow_decimal',
        store=True, readonly=False,
        help="Whether a cashier may sell a fraction, e.g. 2.75 metres or "
             "12.5 kg. Off for pieces, because half a tap is not a thing. "
             "Follows the Measurement Type unless you change it.",
    )
    pos_retail_quick_qty = fields.Char(
        string="Quick Quantities",
        compute='_compute_pos_retail_quick_qty',
        store=True, readonly=False,
        help="Shortcut buttons shown at the till for this item, as a "
             "comma-separated list, e.g. \"0.5, 1, 2, 5, 10\". Leave blank for "
             "no shortcuts. Tapping one sets that quantity outright rather "
             "than adding to it.",
    )
    # Both fields above are stored computes with readonly=False, which makes
    # them editable -- but NOT sticky. Any later change to the Unit re-runs the
    # compute and silently discards whatever the shopkeeper typed: set your own
    # "1, 2, 3, 6, 12" shortcuts, fix a typo in the Unit afterwards, and they
    # are gone with no warning. These flags record "a human chose this", and the
    # computes below leave those records alone.
    pos_retail_measurement_type_manual = fields.Boolean(
        default=False, copy=True,
        help="Technical: set once someone picks a Measurement Type by hand, so "
             "a later Unit change stops overwriting their choice.",
    )
    pos_retail_quick_qty_manual = fields.Boolean(
        default=False, copy=True,
        help="Technical: set once someone types their own Quick Quantities, so "
             "a later Unit change stops overwriting them.",
    )

    # No unit-name field here on purpose: product.template.uom_name already is
    # related='uom_id.name' in core (product_template.py). Adding our own gave
    # two fields labelled "Unit Name", which is the exact duplicate-label
    # problem this module fixed elsewhere. The POS payload below ships core's.

    # --- derivations ----------------------------------------------------

    @api.depends('uom_id', 'pos_retail_measurement_type_manual')
    def _compute_pos_retail_measurement_type(self):
        for tmpl in self:
            if tmpl.pos_retail_measurement_type_manual:
                # Re-assign the stored value rather than skipping: a stored
                # compute that leaves a record untouched is not guaranteed to
                # keep it.
                tmpl.pos_retail_measurement_type = tmpl.pos_retail_measurement_type
                continue
            tmpl.pos_retail_measurement_type = (
                tmpl.uom_id._pos_retail_measurement_type() if tmpl.uom_id else 'piece'
            )

    @api.depends('pos_retail_measurement_type')
    def _compute_pos_retail_allow_decimal(self):
        for tmpl in self:
            tmpl.pos_retail_allow_decimal = (
                tmpl.pos_retail_measurement_type in DECIMAL_TYPES
            )

    @api.depends('pos_retail_measurement_type', 'pos_retail_quick_qty_manual')
    def _compute_pos_retail_quick_qty(self):
        for tmpl in self:
            if tmpl.pos_retail_quick_qty_manual:
                tmpl.pos_retail_quick_qty = tmpl.pos_retail_quick_qty
                continue
            tmpl.pos_retail_quick_qty = DEFAULT_QUICK_QTY.get(
                tmpl.pos_retail_measurement_type, False)

    # --- remembering a human's choice -----------------------------------

    # Flagged in create/write rather than through an inverse: these are stored
    # computes with readonly=False, so Odoo writes the value straight through
    # and no inverse ever runs. Intercepting the write is the only place that
    # can tell "the user set this" from "the compute set this".

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('pos_retail_measurement_type'):
                vals.setdefault('pos_retail_measurement_type_manual', True)
            if vals.get('pos_retail_quick_qty'):
                vals.setdefault('pos_retail_quick_qty_manual', True)
            self._pos_retail_drop_blank_uom(vals)
        return super().create(vals_list)

    @api.model
    def _pos_retail_drop_blank_uom(self, vals):
        """An empty Unit cell means "use the default", not "no unit".

        uom_id is required at database level but carries a default of Units.
        Odoo's importer writes False for an empty cell in a column that IS
        present, and False hits a NOT NULL violation on the raw column before
        any default applies -- so a Unit column in a spreadsheet used to blow up
        the whole import the moment one row left it blank. Removing the key
        instead lets _add_missing_default_values do its job.

        This is what makes it safe to put Unit back in the import sheet at all:
        without it the column can only be included if every single row fills it.
        """
        if 'uom_id' in vals and not vals['uom_id']:
            del vals['uom_id']

    def write(self, vals):
        self._pos_retail_drop_blank_uom(vals)
        # Clearing a field by hand counts as a choice too: emptying Quick
        # Quantities means "no shortcuts", not "give me the defaults back".
        if 'pos_retail_measurement_type' in vals:
            vals.setdefault('pos_retail_measurement_type_manual', True)
        if 'pos_retail_quick_qty' in vals:
            vals.setdefault('pos_retail_quick_qty_manual', True)
        return super().write(vals)

    # --- validation (section 26) ----------------------------------------

    @api.constrains('pos_retail_quick_qty')
    def _check_pos_retail_quick_qty(self):
        """Reject shortcut lists the till could not render.

        Parsing fails loudly here rather than silently dropping a button at the
        register, where nobody would notice the 5 m shortcut had gone missing.
        """
        for tmpl in self:
            for value in tmpl._pos_retail_quick_qty_raw():
                try:
                    number = float(value)
                except ValueError:
                    raise ValidationError(_(
                        "\"%(value)s\" in Quick Quantities is not a number. Use "
                        "a comma-separated list such as \"0.5, 1, 2, 5, 10\".",
                        value=value,
                    ))
                if number <= 0:
                    raise ValidationError(_(
                        "Quick Quantities must all be greater than zero; "
                        "\"%(value)s\" is not.", value=value,
                    ))
                if not tmpl._pos_retail_permits_fractions() and number != int(number):
                    raise ValidationError(_(
                        "\"%(value)s\" is a fraction, but \"%(product)s\" does "
                        "not allow decimal quantities. Either tick Allow "
                        "Decimal Quantity or use whole numbers.",
                        value=value, product=tmpl.display_name,
                    ))

    # There is deliberately NO constraint forcing a measured product to allow
    # decimals. An earlier version had one and it was wrong twice over:
    #
    #  * It fought its own compute. During a bulk import, writing any field in
    #    this dependency chain leaves allow_decimal at its default while
    #    measurement_type has already resolved to 'length'. The constraint saw
    #    that half-built state and rejected the row, so importing a spreadsheet
    #    with a Quick Quantities column failed on every measured product.
    #  * It guarded nothing. _compute_pos_retail_allow_decimal already switches
    #    decimals on for measured goods, so the only way to reach the forbidden
    #    state is to untick the box on purpose, which is a shopkeeper's decision
    #    to make, not a data-integrity violation.
    #
    # The check that does earn its place is the quick-quantity one above: a
    # fractional shortcut on a whole-unit product is unusable, not merely odd.

    # --- helpers --------------------------------------------------------

    def _pos_retail_permits_fractions(self):
        """Whether a fractional quantity makes sense for this product.

        Falls back to the UNIT rather than trusting pos_retail_allow_decimal on
        its own. Constraints run before Odoo has finished cascading the stored
        computes, so during a bulk import that flag is still False on a brand
        new record even when the unit is kilograms. Reading it alone rejected
        "0.5, 1, 5, 10, 25" on a product sold by weight -- a row straight out of
        our own shipped template. uom_id is always present by then, so deriving
        from it is both earlier and more truthful.
        """
        self.ensure_one()
        if self.pos_retail_allow_decimal:
            return True
        kind = self.uom_id._pos_retail_measurement_type() if self.uom_id else 'piece'
        return kind in DECIMAL_TYPES

    def _pos_retail_quick_qty_raw(self):
        self.ensure_one()
        return [p.strip() for p in (self.pos_retail_quick_qty or '').split(',') if p.strip()]

    def pos_retail_quick_qty_list(self):
        """Shortcut quantities as floats, for the till. Never raises: the
        constraint above already rejected anything unparseable on save, so a
        bad value here would mean hand-edited data and is simply skipped."""
        self.ensure_one()
        out = []
        for value in self._pos_retail_quick_qty_raw():
            try:
                out.append(float(value))
            except ValueError:
                continue
        return out

    @api.model
    def _load_pos_data_fields(self, config):
        result = super()._load_pos_data_fields(config)
        for field in ('pos_retail_measurement_type', 'pos_retail_allow_decimal',
                      'pos_retail_quick_qty', 'uom_name'):
            if field not in result:
                result.append(field)
        return result
